name: christian_270_project
channels:
 - conda-forge
dependencies:
 - r-base=4.1
 - r-pacman=0.5.1
 - r-data.table=1.14.2
 - r-ggplot2=3.3.5
 - r-rcurl=1.98.1.9
 - r-tidyverse=1.3.1
 - r-knitr=1.37
 - r-kableextra=1.3.4
 - r-ggsci=2.9